# Generated by Django 5.0 on 2023-12-14 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=60)),
                ('adress', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.CharField(max_length=6)),
                ('date', models.DateField(auto_now=True)),
                ('state', models.CharField(max_length=30)),
                ('finance', models.IntegerField()),
                ('id_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_money', models.FloatField()),
                ('date_prog', models.DateField()),
                ('date_input', models.DateField(auto_now=True)),
                ('id_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
                ('id_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.invoice')),
                ('id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.product')),
            ],
        ),
    ]
